doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        options:
            1001: true
            1000: false
        mapping_types:
            enum: string

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Products:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Products/Infrastructure/Database/ORM'
                prefix: 'App\Products\Domain\Entity'
                alias: Products


when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
